In [1]:
#getting information from tensors
"""
when not in datatype - use tensor.dtype
when not in right shape - use tensor.shape
when not on the right device - use tensor.device
"""


'\nwhen not in datatype - use tensor.dtype\nwhen not in right shape - use tensor.shape\nwhen not on the right device - use tensor.device\n'

In [2]:
#create a tensor
import torch 
some_tensor = torch.rand(3, 4)
some_tensor

/Users/taewoohong/dev/git/CppPyPlayGround/learnPyTorch/tensors/.env3.12/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


tensor([[0.4313, 0.7975, 0.8376, 0.9959],
        [0.1499, 0.3863, 0.1267, 0.4206],
        [0.7592, 0.8025, 0.2916, 0.8944]])

In [5]:
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device of tensor is on: {some_tensor.device}')

tensor([[0.4313, 0.7975, 0.8376, 0.9959],
        [0.1499, 0.3863, 0.1267, 0.4206],
        [0.7592, 0.8025, 0.2916, 0.8944]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor is on: cpu


In [8]:
#Manipulation of Tensors
"""
Tensor operation includes:
addition
subtraction
multiplication
devision
matrix mulplication
"""


'\nTensor operation includes:\naddition\nsubtraction\nmultiplication\ndevision\nmatrix mulplication\n'

In [13]:
tensor = torch.tensor([1, 2, 4])
tensor
tensor + 5

tensor([6, 7, 9])

In [15]:
tensor * 10

tensor([10, 20, 40])

In [17]:
tensor - 4

tensor([-3, -2,  0])

In [19]:
#pytorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 40])

In [21]:
torch.add(tensor, 10)

tensor([11, 12, 14])

In [24]:
torch.sub(tensor, 5)

tensor([-4, -3, -1])

In [26]:
#matrix multiplication
"""
two ways of performing multiplication in neural networks and deep learning
matrix multiplication
element-wise mutiplication
"""

'\ntwo ways of performing multiplication in neural networks and deep learning\nmatrix multiplication\nelement-wise mutiplication\n'

In [35]:
#element wise multiplcation
print(tensor, " * ", tensor)


tensor([1, 2, 4])  *  tensor([1, 2, 4])


print(f"Equals: {tensor * tensor}")

In [31]:
torch.matmul(tensor, tensor)

tensor(21)

In [33]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(21)
CPU times: user 1.05 ms, sys: 884 µs, total: 1.94 ms
Wall time: 1.14 ms


In [36]:
%%time
torch.matmul(tensor, tensor)


CPU times: user 219 µs, sys: 83 µs, total: 302 µs
Wall time: 296 µs


tensor(21)

In [37]:
##biggest error in deep learning is shape error especially on big tensors
"""
There are two rules that performing matrix multiplcation needs to satisfy:
1. inner dimesnions must match:
* '(3, 2) @ (3,2)' will not work.
* '(3, 2) @ (2,3)' will work.
* '(2, 3) @ (3,2)' will work.

2. resulting matrix has the shape fo the outer dimensionn:
* '(3,2) @ (2,3)' results in '(3,3)'
* '(2,3) @ (3,2)' results in '(2,2)'
"""

"\nThere are two rules that performing matrix multiplcation needs to satisfy:\n1. inner dimesnions must match:\n* '(3, 2) @ (3,2)' will not work.\n* '(3, 2) @ (2,3)' will work.\n* '(2, 3) @ (3,2)' will work.\n"

In [57]:
torch.matmul(torch.rand(4,3,2), torch.rand(4,2,7)).shape

torch.Size([4, 3, 7])

In [58]:
### Shape for matrix multiplicationt
tensor_A = torch.tensor([[1,4],
                         [3,4],
                         [4,2]])

tensor_B = torch.tensor([[3,7],
                         [1,9],
                         [8,5]])

#torch.mm = torch.matmul
#this will throw an error because the shapes are not compatible for matrix multiplication
torch.mm(tensor_A, tensor_B)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [66]:
#to fix shape error we can use transpose.
"""
Transpose will switch axes of a given tensor.
"""

torch.mm(tensor_A, tensor_B.T)

tensor([[31, 37, 28],
        [37, 39, 44],
        [26, 22, 42]])