In [28]:
import torch

vector = torch.rand(2,2,3,2,4)
print(vector)
print(vector.shape)

tensor([[[[[0.3664, 0.5402, 0.5869, 0.8210],
           [0.9548, 0.9737, 0.7270, 0.1885]],

          [[0.2613, 0.2145, 0.5823, 0.3938],
           [0.7884, 0.3322, 0.3702, 0.4349]],

          [[0.7682, 0.6950, 0.2328, 0.4557],
           [0.1072, 0.7214, 0.0417, 0.6986]]],


         [[[0.1977, 0.7425, 0.5510, 0.0224],
           [0.7958, 0.7609, 0.0934, 0.2220]],

          [[0.6240, 0.7573, 0.3063, 0.7584],
           [0.1759, 0.9950, 0.5653, 0.0854]],

          [[0.2809, 0.7894, 0.9922, 0.2251],
           [0.9484, 0.0332, 0.1574, 0.1297]]]],



        [[[[0.2337, 0.1953, 0.4512, 0.2566],
           [0.2141, 0.0713, 0.5563, 0.7579]],

          [[0.3034, 0.2207, 0.3389, 0.4729],
           [0.1344, 0.1428, 0.6239, 0.5476]],

          [[0.3043, 0.0499, 0.2007, 0.2037],
           [0.5171, 0.6784, 0.8129, 0.3237]]],


         [[[0.0111, 0.8201, 0.4915, 0.4738],
           [0.3528, 0.9735, 0.1611, 0.5291]],

          [[0.1122, 0.7690, 0.5817, 0.8713],
           [0.5919, 0.4444,

In [36]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float64,
                               device=None,
                               requires_grad=False)

float_64_tensor.dtype

torch.float64

In [39]:
#Converting floats
float_32_tensor = float_64_tensor.type(torch.float32)
float_32_tensor.dtype

print(float_32_tensor)

tensor([3., 6., 9.])


In [41]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [43]:
float_64_tensor / float_32_tensor

tensor([1., 1., 1.], dtype=torch.float64)

In [46]:
int_32_tensor = torch.tensor([3,2,8],
                             dtype=torch.int32)

int_32_tensor

tensor([3, 2, 8], dtype=torch.int32)

In [48]:
float_32_tensor * int_32_tensor


tensor([ 9., 12., 72.])

In [51]:
int_32_tensor = torch.tensor([3,8,12], dtype=torch.long)
int_32_tensor.dtype

torch.int64

In [52]:
int_32_tensor * float_32_tensor

tensor([  9.,  48., 108.])