In [7]:
import torch

#create tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [8]:
#get min
torch.min(x)
x.min()

tensor(0)

In [9]:
#get max
torch.max(x)
x.max()

tensor(90)

In [10]:
#find the mean
#this will throw an error
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [11]:
#to fix this error convert or use float
torch.mean(x.float())
#torch mean requires tensor of float32 or similar datatype to work.
x = x.type(torch.float32)
x.mean()

tensor(45.)

In [12]:
#find the sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

In [13]:
#experiment with aggregating tensors
tens2 = torch.rand(2, 2)
tens2

tensor([[0.7890, 0.9784],
        [0.4140, 0.2861]])

In [14]:
tens2.min()

tensor(0.2861)

In [15]:
tens2.sum()

tensor(2.4674)

In [16]:
tens2.mean()

tensor(0.6168)

## Finding the position min and max

In [17]:
# find the position in tensor with minimum value in index
x = torch.arange(1, 100, 10)
x.argmin()

tensor(0)

In [18]:
#find the max
x.argmax()

tensor(9)

## Reshaping, stacking, squeezing, and unsqueezing

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain chape but keep the same memory as the original tensor
* stacking - combine multiple tensors on top of each other (vstack) (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - adds a 1 dimension to a target tensor
* Permute = return a view of the input with dimensions permuted (swapped) in a certain way

In [19]:
import torch

x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [20]:
# add an extra dimension - dimensions has to be compatible with original
x_reshaped = x.reshape(1, 10)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [21]:
#this works too! as long as we are not adding elements
x_reshaped = x.reshape(5, 2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [22]:
#change the view 
#view vs reshape is that view SHARES THE SAME MEMORY as original.
z = x.view(2, 5)

In [23]:
#changing z WILL CHANGE X and VICE VERSA
x[: 0] = 5
x, z

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]))

In [31]:
# stack tensors on top of each other.
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [38]:
#torch.squeeze removes all single dimensions.
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [39]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [42]:
y = torch.squeeze(x, 0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [44]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [46]:
y = torch.squeeze(x, 2)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [60]:
x_reshaped = x_reshaped.reshape(1,10)
x_reshaped
print(f"Previous tensor: {x_reshaped}")
print(f'\nPrevious shape: {x_reshaped.shape}')

Previous tensor: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

Previous shape: torch.Size([1, 10])


In [62]:
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"\nNew shape: {x_squeezed.shape}")


New tensor: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

New shape: torch.Size([10])


In [65]:
#torch unqueeze() adds a single dimenesion to a target tensor at a specific dim
print(f"Previous target: {x_squeezed}")
print(f"Previous shape:  {x_squeezed.shape}")


# add an extra dimension
x_unsqueeze = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueeze}")
print(f"New shape: {x_unsqueeze.shape}")

Previous target: tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape:  torch.Size([10])

New tensor: tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [66]:
#torch permute - rearranges the dimensions of a target tensor
x_original = torch.rand(size=(224, 224, 3)) #[height, width, color_channel]

#permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # [color_channel, height, width]

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
#NOTED THAT PERMUTED SHARE THE SAME MEMORY AS ORIGINAL!!!

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])
